-- =========================================
-- BARIAPLUS DATABASE SCHEMA
-- =========================================

-- TABLAS PRINCIPALES
CREATE TABLE IF NOT EXISTS "genders" (
                                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "name" varchar(10)
    );

CREATE TABLE IF NOT EXISTS "doctors" (
                                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "first_name" varchar(50) NOT NULL,
    "last_name" varchar(50) NOT NULL,
    "professional_license_number" varchar(20) UNIQUE NOT NULL,
    "employment_start_date" date NOT NULL,
    "graduation_institution" varchar(150) NOT NULL,
    "current_workplace" varchar(150) NOT NULL,
    "email" varchar(255) NOT NULL,
    "password_hash" varchar(255) NOT NULL,
    "gender_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "patient_status"(
                                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               "name" varchar(10) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "patients" (
                                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "first_name" varchar(50) NOT NULL,
    "last_name" varchar(50) NOT NULL,
    "date_of_birth" date NOT NULL,
    "doctor_id" int NOT NULL,
    "gender_id" int NOT NULL,
    "status_id" int NOT NULL,
    "emergency_number" varchar(20) NOT NULL,
    "entry_date" date NOT NULL
    );

CREATE TABLE IF NOT EXISTS "allergies" (
                                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "name" varchar(20) NOT NULL,
    "allergic_reaction" varchar(255) NOT NULL,
    "patient_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "history_types" (
                                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               "name" varchar(50)
    );

CREATE TABLE IF NOT EXISTS "medical_histories" (
                                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   "detection_date" date,
                                                   "name" varchar(20) NOT NULL,
    "patient_id" int NOT NULL,
    "history_types_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "actual_state"(
                                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             "name" varchar(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "diseases" (
                                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "name" varchar(100) NOT NULL,
    "actual_state_id" int NOT NULL,
    "patient_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "medical_records" (
                                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "patient_id" int UNIQUE NOT NULL,
                                                 "creation_date" date NOT NULL
);

CREATE TABLE IF NOT EXISTS "medical_consultations" (
                                                       "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       "date" date NOT NULL,
                                                       "reason" varchar(100) NOT NULL,
    "medical_records_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "note_categories" (
                                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "name" varchar(50)
    );

CREATE TABLE IF NOT EXISTS "notes" (
                                       "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "description" text NOT NULL,
                                       "medical_consultation_id" int NOT NULL,
                                       "category_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "reviews" (
                                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "puntuation" int NOT NULL,
                                         "comments" text NOT NULL,
                                         "date" Date NOT NULL,
                                         "medical_consultation_id" int UNIQUE
);

CREATE TABLE IF NOT EXISTS "measurement_units" (
                                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   "name" varchar(10) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "type_indicators" (
                                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "name" varchar(50),
    "measurement_unit_id" int
    );

CREATE TABLE IF NOT EXISTS "health_indicators" (
                                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   "value" decimal(5,2) NOT NULL,
    "type_indicator_id" int NOT NULL,
    "medical_consultation_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "ranges" (
                                        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "name" varchar(100)
    );

CREATE TABLE IF NOT EXISTS "range_details" (
                                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               "range_id" int NOT NULL,
                                               "gender_id" int,
                                               "min_age" int,
                                               "max_age" int,
                                               "min_value" decimal(5,2),
    "max_value" decimal(5,2),
    "type_indicators_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "category_metric" (
                                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "name" varchar(30)
    );

CREATE TABLE IF NOT EXISTS "metrics_catalog" (
                                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "name" varchar(30),
    "measurement_unit_id" int,
    "category_metric_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "metrics_value" (
                                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               "metrics_catalog_id" int NOT NULL,
                                               "value" decimal(7,2),
    "medical_consultation_id" int NOT NULL
    );

CREATE TABLE IF NOT EXISTS "physical_activity_levels"(
                                                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                         "name" VARCHAR(50) NOT NULL,
    "description" varchar(255),
    "activity_factor" DECIMAL(4,3) NOT NULL
    );

CREATE TABLE IF NOT EXISTS "energetic_expenditure" (
                                                       "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       "medical_consultation_id" int NOT NULL,
                                                       "physical_activity_id" INT,
                                                       "value" DECIMAL(7,2) NOT NULL,
    "reduction_percentage" DECIMAL(5,2),
    "adjusted_value" DECIMAL(7,2)
    );

-- DATOS INICIALES
INSERT INTO note_categories (name)
SELECT * FROM (VALUES
                   ('Estado emocional'),
                   ('Calidad de sueño'),
                   ('Dieta'),
                   ('Opinión dieta'),
                   ('Evolucion del paciente'),
                   ('Terapia Farmacologica'),
                   ('Alimentos'),
                   ('Recordatorio 24 h')
              ) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM note_categories LIMIT 1);

INSERT INTO history_types (name)
SELECT * FROM (VALUES
                   ('Personales patológicos'),
                   ('Personales no patológicos'),
                   ('Heredofamiliares'),
                   ('Quirúrgicos'),
                   ('Ginecobstétrico'),
                   ('Tratamientos de Obesidad')
              ) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM history_types LIMIT 1);

INSERT INTO genders (name)
SELECT * FROM (VALUES ('Femenino'), ('Masculino')) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM genders LIMIT 1);

INSERT INTO category_metric (name)
SELECT * FROM (VALUES
                   ('Mediciones básicas'),
                   ('Circunferencias'),
                   ('Pliegues'),
                   ('Bioimpedencia')
              ) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM category_metric LIMIT 1);

INSERT INTO patient_status(name)
SELECT * FROM (VALUES ('Activo'), ('Inactivo')) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM patient_status LIMIT 1);

INSERT INTO actual_state (name)
SELECT * FROM (VALUES
                   ('Crónica'),
                   ('En remisión'),
                   ('Estable'),
                   ('Progresiva')
              ) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM actual_state LIMIT 1);

INSERT INTO measurement_units(name)
SELECT * FROM (VALUES
                   ('%'), ('kg'), ('kg/m2'), ('cm'), ('mm'), ('kcal'), ('cal'), ('años')
              ) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM measurement_units LIMIT 1);

INSERT INTO metrics_catalog (name, category_metric_id, measurement_unit_id)
SELECT * FROM (VALUES
                   ('Peso', 1, 2), ('Talla', 1, 4), ('Peso Brocca', 1, 2), ('Peso Lorentz', 1, 2), ('Peso ideal (promedio)', 1, 2),
                   ('Cintura', 2, 4), ('Cadera', 2, 4), ('Muñeca', 2, 4), ('Brazo relajado', 2, 4), ('Cuello', 2, 4), ('Muslo', 2, 4), ('Contraído', 2, 4),
                   ('Bíceps', 3, 5), ('Tríceps', 3, 5), ('Subescapular', 3, 5), ('Ileocrestal', 3, 5), ('Suprailiaco', 3, 5), ('Abdominal', 3, 5), ('Axila medial', 3, 5), ('Pectoral', 3, 5), ('Suma de piegues', 3, 5),
                   ('Porcentaje de grasa corporal', 4, 1), ('Kg de músculo', 4, 2), ('Kg Masa ósea', 4, 2), ('Porcentaje de agua corporal', 4, 1), ('Ingestión diaria en calorias', 4, 7), ('Edad metabólica', 4, 8), ('IMC(BMI)', 4, 3), ('Nivel de grasa visceral', 4, NULL), ('Proporción de grasa visceral', 4, 1)
              ) AS v(name, category_metric_id, measurement_unit_id)
WHERE NOT EXISTS (SELECT 1 FROM metrics_catalog LIMIT 1);

INSERT INTO ranges (name)
SELECT * FROM (VALUES
                   ('Demasiado Bajo'), ('Bajo'), ('Normal'), ('Saludable'), ('Alto'), ('Sobrepeso'), ('Obesidad'), ('Aceptable'), ('Bueno'), ('Peligroso'), ('Insuficiencia ponderal'), ('Intervalo normal'), ('Preobesidad'), ('Obesidad clase I'), ('Obesidad clase II'), ('Obesidad clase III')
              ) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM ranges LIMIT 1);

INSERT INTO type_indicators (name, measurement_unit_id)
SELECT * FROM (VALUES
                   ('IMC', 3), ('Porcentaje de Grasa Corporal', 1), ('Porcentaje de Grasa Visceral', 1), ('Porcentaje de Masa Muscular', 1), ('Índice cintura cadera', NULL)
              ) AS v(name, measurement_unit_id)
WHERE NOT EXISTS (SELECT 1 FROM type_indicators LIMIT 1);

INSERT INTO physical_activity_levels (name, description, activity_factor)
SELECT * FROM (VALUES
                   ('Sedentario', 'Poco o ningún ejercicio', 1.200),
                   ('Ligero', 'Ejercicio ligero 1–3 días/semana', 1.375),
                   ('Moderado', 'Ejercicio moderado 3–5 días/semana', 1.550),
                   ('Intenso', 'Ejercicio intenso 6–7 días/semana', 1.725),
                   ('Muy intenso', 'Entrenamiento muy fuerte o trabajo físico pesado', 1.900)
              ) AS v(name, description, activity_factor)
WHERE NOT EXISTS (SELECT 1 FROM physical_activity_levels LIMIT 1);

-- RANGOS (solo si no existen datos)
INSERT INTO range_details (type_indicators_id, range_id, gender_id, min_age, max_age, min_value, max_value)
SELECT * FROM (VALUES
                   (1, 11, NULL, NULL, NULL, NULL, 18.49),
                   (1, 12, NULL, NULL, NULL, 18.5, 24.9),
                   (1, 13, NULL, NULL, NULL, 25.0, 29.9),
                   (1, 14, NULL, NULL, NULL, 30.0, 34.9),
                   (1, 15, NULL, NULL, NULL, 35.0, 39.9),
                   (1, 16, NULL, NULL, NULL, 40.0, NULL),
                   (2, 1, 1, 18, 39, NULL, 16.99),
                   (2, 4, 1, 18, 39, 17.0, 30.0),
                   (2, 6, 1, 18, 39, 30.01, 36.0),
                   (2, 7, 1, 18, 39, 36.01, NULL),
                   (2, 1, 1, 40, 59, NULL, 21.99),
                   (2, 4, 1, 40, 59, 22.0, 33.0),
                   (2, 6, 1, 40, 59, 33.01, 40.0),
                   (2, 7, 1, 40, 59, 40.01, NULL),
                   (2, 1, 1, 60, NULL, NULL, 22.99),
                   (2, 4, 1, 60, NULL, 23.0, 35.0),
                   (2, 6, 1, 60, NULL, 35.01, 41.0),
                   (2, 7, 1, 60, NULL, 41.01, NULL),
                   (2, 1, 2, 18, 39, NULL, 7.99),
                   (2, 4, 2, 18, 39, 8.0, 19.0),
                   (2, 6, 2, 18, 39, 19.01, 23.0),
                   (2, 7, 2, 18, 39, 23.01, NULL),
                   (2, 1, 2, 40, 59, NULL, 9.99),
                   (2, 4, 2, 40, 59, 10.0, 21.0),
                   (2, 6, 2, 40, 59, 21.01, 27.0),
                   (2, 7, 2, 40, 59, 27.01, NULL),
                   (2, 1, 2, 60, NULL, NULL, 11.99),
                   (2, 4, 2, 60, NULL, 12.0, 23.0),
                   (2, 6, 2, 60, NULL, 23.01, 29.0),
                   (2, 7, 2, 60, NULL, 29.01, NULL),
                   (3, 8, NULL, NULL, NULL, 1.0, 5.0),
                   (3, 9, NULL, NULL, NULL, 5.01, 10.0),
                   (3, 10, NULL, NULL, NULL, 10.01, 15.0),
                   (3, 10, NULL, NULL, NULL, 15.01, NULL),
                   (4, 2, 1, NULL, NULL, NULL, 23.99),
                   (4, 3, 1, NULL, NULL, 24.0, 30.0),
                   (4, 5, 1, NULL, NULL, 30.01, NULL),
                   (4, 2, 2, NULL, NULL, NULL, 33.99),
                   (4, 3, 2, NULL, NULL, 34.0, 40.0),
                   (4, 5, 2, NULL, NULL, 40.01, NULL),
                   (5, 3, 1, NULL, NULL, NULL, 0.85),
                   (5, 10, 1, NULL, NULL, 0.85, NULL),
                   (5, 3, 2, NULL, NULL, NULL, 1.0),
                   (5, 10, 2, NULL, NULL, 1.0, NULL)
              ) AS v(type_indicators_id, range_id, gender_id, min_age, max_age, min_value, max_value)
WHERE NOT EXISTS (SELECT 1 FROM range_details LIMIT 1);

-- FOREIGN KEYS (solo se crean si no existen)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'doctors_gender_id_fkey') THEN
ALTER TABLE "doctors" ADD FOREIGN KEY ("gender_id") REFERENCES "genders" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'patients_gender_id_fkey') THEN
ALTER TABLE "patients" ADD FOREIGN KEY ("gender_id") REFERENCES "genders" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'patients_doctor_id_fkey') THEN
ALTER TABLE "patients" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctors" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'patients_status_id_fkey') THEN
ALTER TABLE "patients" ADD FOREIGN KEY ("status_id") REFERENCES "patient_status" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'medical_records_patient_id_fkey') THEN
ALTER TABLE "medical_records" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allergies_patient_id_fkey') THEN
ALTER TABLE "allergies" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'diseases_patient_id_fkey') THEN
ALTER TABLE "diseases" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'diseases_actual_state_id_fkey') THEN
ALTER TABLE "diseases" ADD FOREIGN KEY ("actual_state_id") REFERENCES "actual_state" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'medical_histories_patient_id_fkey') THEN
ALTER TABLE "medical_histories" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'medical_histories_history_types_id_fkey') THEN
ALTER TABLE "medical_histories" ADD FOREIGN KEY ("history_types_id") REFERENCES "history_types" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'medical_consultations_medical_records_id_fkey') THEN
ALTER TABLE "medical_consultations" ADD FOREIGN KEY ("medical_records_id") REFERENCES "medical_records" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notes_medical_consultation_id_fkey') THEN
ALTER TABLE "notes" ADD FOREIGN KEY ("medical_consultation_id") REFERENCES "medical_consultations" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notes_category_id_fkey') THEN
ALTER TABLE "notes" ADD FOREIGN KEY ("category_id") REFERENCES "note_categories" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reviews_medical_consultation_id_fkey') THEN
ALTER TABLE "reviews" ADD FOREIGN KEY ("medical_consultation_id") REFERENCES "medical_consultations" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'health_indicators_medical_consultation_id_fkey') THEN
ALTER TABLE "health_indicators" ADD FOREIGN KEY ("medical_consultation_id") REFERENCES "medical_consultations" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'health_indicators_type_indicator_id_fkey') THEN
ALTER TABLE "health_indicators" ADD FOREIGN KEY ("type_indicator_id") REFERENCES "type_indicators" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'type_indicators_measurement_unit_id_fkey') THEN
ALTER TABLE "type_indicators" ADD FOREIGN KEY ("measurement_unit_id") REFERENCES "measurement_units" ("id");
END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'metrics_catalog_category_metric_id_fkey') THEN
ALTER TABLE "metrics_catalog" ADD FOREIGN KEY ("category_metric_id") REFERENCES "category_metric" ("id");
END IF;
  
  IF NOT